import { type ClassValue, clsx } from "clsx"
import { twMerge } from "tailwind-merge"
import fixWebmDuration from "webm-duration-fix"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

/**
 * Fixes WebM metadata (duration) for blobs generated by MediaRecorder API
 * Uses webm-duration-fix which handles large files efficiently with blob.stream()
 * @param webmBlob - The WebM blob to fix
 * @returns Promise resolving to a fixed WebM blob
 */
export async function fixWebmMetadata(webmBlob: Blob): Promise<Blob> {
  // Only fix if it's a WebM blob
  if (!webmBlob.type.includes('webm')) {
    return webmBlob
  }

  try {
    const fixedBlob = await fixWebmDuration(webmBlob)
    return fixedBlob
  } catch (error) {
    console.error('Error fixing WebM metadata:', error)
    // Return original blob if fix fails
    return webmBlob
  }
}
